logging:
  level: DEBUG
  loggers:
    net.kpw: DEBUG
    org.eclipse.jetty: INFO
    org.apache.http: INFO
httpClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
  userAgent: idiotbot