logging:
  level: DEBUG
  loggers:
    net.kpw: DEBUG
    org.eclipse.jetty: INFO
    org.apache.http: INFO
    com.codahale.metrics.httpclient: INFO
    
httpClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
  userAgent: slackboat
  
slack:
  clientID: '261022332754.262110268791'
  clientSecret: 'a23d94391017b58ff8a04eaaab29f02f'
  verificationToken: 'oxQEQTZ1Ql11KhfVNhQbbnlr'
